server:
    port: 10480
    error:
        include-message: always
spring:
    application:
        name: blss-labs
    jta:
        atomikos:
            datasource:
                primary:
                    max-pool-size: 10
                    unique-resource-name: primary
                    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
                    xa-properties:
                        url: jdbc:postgresql://localhost:5432/blps
                        user: postgres
                        password: qwerty123
                secondary:
                    max-pool-size: 10
                    unique-resource-name: secondary
                    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
                    xa-properties:
                        url: jdbc:postgresql://localhost:5432/stupid_db
                        user: postgres
                        password: qwerty123
            properties:
                log-base-dir: ./atomikos-logs
    jpa:
        properties:
            hibernate:
                connection:
                    handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
                hbm2ddl:
                    auto: update
                show_sql: true
                format_sql: false
                physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
                implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    kafka:
        producer:
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: levit104.blss.labs.messaging
            group-id: users
