server:
    port: 10480
    error:
        include-message: always
spring:
    application:
        name: blss-labs
    jta:
        atomikos:
            datasource:
                main:
                    max-pool-size: 10
                    unique-resource-name: main
                    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
                    xa-properties:
                        url: jdbc:postgresql://localhost:5432/blps
                        user: postgres
                        password: qwerty123
                secondary:
                    max-pool-size: 10
                    unique-resource-name: secondary
                    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
                    xa-properties:
                        url: jdbc:postgresql://localhost:5432/stupid_db
                        user: postgres
                        password: qwerty123
    jpa:
        properties:
            hibernate:
                connection:
                    handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
                hbm2ddl:
                    auto: update
                show_sql: true
                format_sql: false
                physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
                implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
