server:
    port: 10480
    error:
        include-message: always
spring:
    application:
        name: BlpsLab1
    jta:
        atomikos:
            datasource:
                main:
                    max-pool-size: 10
                    unique-resource-name: main
                    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
                    xa-properties:
                        url: jdbc:postgresql://localhost:5432/blps
                        user: postgres
                        password: qwerty123
                secondary:
                    max-pool-size: 10
                    unique-resource-name: secondary
                    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
                    xa-properties:
                        url: jdbc:postgresql://localhost:5432/stupid_db
                        user: postgres
                        password: qwerty123